/cs/ep/120/playground/Voice-Image-Classifier/.env/lib/python3.9/site-packages/transformers/utils/hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/cs/ep/120/playground/Voice-Image-Classifier/.env/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/cs/ep/120/Voice-Image-Classifier/models/training.py", line 157, in <module>
    app.run(main)
  File "/cs/ep/120/playground/Voice-Image-Classifier/.env/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/cs/ep/120/playground/Voice-Image-Classifier/.env/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/cs/ep/120/Voice-Image-Classifier/models/training.py", line 153, in main
    train(train_dataloader, validation_dataloader, model, cosine_similarity_loss, optimizer, num_epochs=EPOCHS.value)
  File "/cs/ep/120/Voice-Image-Classifier/models/training.py", line 107, in train
    for Batch_number, (images, voices) in enumerate(train_data_loader):
  File "/cs/ep/120/playground/Voice-Image-Classifier/.env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/cs/ep/120/playground/Voice-Image-Classifier/.env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/cs/ep/120/playground/Voice-Image-Classifier/.env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/cs/ep/120/playground/Voice-Image-Classifier/.env/lib/python3.9/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/cs/ep/120/playground/Voice-Image-Classifier/.env/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/cs/ep/120/playground/Voice-Image-Classifier/.env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/cs/ep/120/Voice-Image-Classifier/models/data_loader.py", line 65, in custom_collate_fn
    images = self.dino.get_embedding(images)
  File "/cs/ep/120/Voice-Image-Classifier/models/image_embedding.py", line 20, in get_embedding
    inputs = self.processor(images=images, return_tensors="pt", do_rescale=False).to(self.device)
  File "/cs/ep/120/playground/Voice-Image-Classifier/.env/lib/python3.9/site-packages/transformers/feature_extraction_utils.py", line 231, in to
    new_data[k] = v.to(*args, **kwargs)
  File "/cs/ep/120/playground/Voice-Image-Classifier/.env/lib/python3.9/site-packages/torch/cuda/__init__.py", line 279, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

